variables:
  # Act as a varibale to be used further in YML file.
  TARGET_FOLDER_NAME: "target"
  BACKEND_FOLDER_NAME: "backend"

stages:
  - build
  - test

backend-build:
  stage: build
  tags:
    - ugrad
  image: maven:latest
  script:
    - echo "Started building backend application."
    - cd backend
    - mvn clean package
    - echo "Backend application has been built successfully."
  rules:
    - changes:
        - backend/**/*
  artifacts:
    when: on_success
    paths:
      - $TARGET_FOLDER_NAME

backend-test:
  stage: test
  tags:
    - ugrad
  image: maven:latest
  script:
    - echo "Backend application test started."
    - cd backend
    - mvn test
    - echo "Backend application Tested successfully."
  rules:
    - changes:
        - backend/**/*
