variables:
  # Act as a varibale to be used further in YML file.
  TARGET_FOLDER_NAME: "target"
  BACKEND_FOLDER_NAME: "backend"
  FRONTEND_FOLDER_NAME: "shipogle-frontend"

stages:
  - build
  - test
  - quality

backend-build:
  stage: build
  tags:
    - ugrad
  image: maven:latest
  script:
    - echo "Started building backend application."
    - cd backend
    - mvn clean package
    - echo "Backend application has been built successfully."
  rules:
    - changes:
        - backend/**/*
  artifacts:
    when: on_success
    paths:
      - $TARGET_FOLDER_NAME

backend-test:
  stage: test
  tags:
    - ugrad
  image: maven:latest
  script:
    - echo "Backend application test started."
    - cd backend
    - ls
    - mvn test
    - echo "Backend application Tested successfully."
  rules:
    - changes:
        - backend/**/*
        
code-quality:
  stage: quality
  tags:
    - ugrad
  image: maven:latest
  script:
    - echo "Code quality job started"
    - mkdir code-smells/
    - java -jar $CI_PROJECT_DIR/DesigniteJava.jar -i $CI_PROJECT_DIR/backend -o codeSmells/ -d
  artifacts:
    paths:
      - codeSmells/