variables:
  # Act as a varibale to be used further in YML file.
  TARGET_FOLDER_NAME: "target"
  BACKEND_FOLDER_NAME: "backend"
  FRONTEND_FOLDER_NAME: "shipogle-frontend"

stages:
  - build
  - test
  - quality
  - deploy

backend-build:
  stage: build
  tags:
    - ugrad
  image: maven:latest
  script:
    - echo "Started building backend application."
    - cd backend
    - mvn clean package
    - echo "Backend application has been built successfully."
  rules:
    - changes:
        - backend/**/*
  artifacts:
    when: on_success
    paths:
      - $BACKEND_FOLDER_NAME/$TARGET_FOLDER_NAME

backend-test:
  stage: test
  tags:
    - ugrad
  image: maven:latest
  script:
    - echo "Backend application test started."
    - cd backend
    - ls
    - mvn test
    - echo "Backend application Tested successfully."
  rules:
    - changes:
        - backend/**/*

code-quality:
  stage: quality
  tags:
    - ugrad
  image: maven:latest
  script:
    - echo "Code quality job started"
    - mkdir code-smells/
    - java -jar $CI_PROJECT_DIR/DesigniteJava.jar -i $CI_PROJECT_DIR/backend -o codeSmells/ -d
  artifacts:
    paths:
      - codeSmells/

backend-deploy:
  stage: deploy
  image: maven:latest
  tags:
    - ugrad
  script:
    - cd backend
    - chmod og-rwx ${VM_PRIVATE_KEY}
    - scp -r -o StrictHostKeyChecking=no -i ${VM_PRIVATE_KEY} ${TARGET_FOLDER_NAME}/Shipogle.jar csci5308vm9@csci5308vm9.research.cs.dal.ca:${BACKEND_FOLDER_NAME}/Shipogle.jar
    - ssh -i ${VM_PRIVATE_KEY} csci5308vm9@csci5308vm9.research.cs.dal.ca "./${BACKEND_FOLDER_NAME}/start_silent.sh"
  only:
    refs:
      - master
  dependencies:
    - backend-build

frontend-deploy:
  stage: deploy
  before_script:
    - apt-get update && apt-get install -y zip
  tags:
    - ugrad
  script:
    - chmod og-rwx ${VM_PRIVATE_KEY}
    - zip -r shipogle-frontend.zip shipogle-frontend
    - scp -r -o StrictHostKeyChecking=no -i ${VM_PRIVATE_KEY} shipogle-frontend.zip csci5308vm9@csci5308vm9.research.cs.dal.ca:${FRONTEND_FOLDER_NAME}/shipogle-frontend.zip
    - ssh -i ${VM_PRIVATE_KEY} csci5308vm9@csci5308vm9.research.cs.dal.ca "./${FRONTEND_FOLDER_NAME}/start_silent.sh"
  only:
    refs:
      - master
