variables:
  # Act as a varibale to be used further in YML file.
  TARGET_FOLDER_NAME: "target"
  BACKEND_FOLDER_NAME: "backend"

default:
  # Providing default image as openjdk:11
  image: openjdk:11

stages:
  # builds shipogle application.
  - build

  # tests shipogle application.
  - test

  # deploys shipogle application
  - deploy

backend-build:
  stage: build
  tags:
    - ugrad
  image: maven:latest
  script:
    - echo "Started building backend application."
    - cd backend
    - mvn clean package
    - echo "Backend application has been built successfully."
  rules:
    - changes:
        - backend/**/*
  artifacts:
    when: on_success
    paths:
      - $TARGET_FOLDER_NAME/*.war

backend-test:
  stage: test
  tags:
    - ugrad
  image: maven:latest
  script:
    - echo "Backend application test started."
    - cd backend
    - mvn test
    - echo "Backend application Tested successfully."
  rules:
    - changes:
        - backend/**/*

backend-deploy:
  image: maven:latest
  stage: deploy
  script:
    - echo "Backend Deployment started"
    - cd $BACKEND_FOLDER_NAME
    - mvn clean package
    - mvn package -B
    - sshpass -V                                                                                                                                
    - export SSHPASS=$CI_USER_PASS                                                                                                              
    - sshpass -e scp -o StrictHostKeyChecking=no $BACKEND_FOLDER_NAME/$TARGET_FOLDER_NAME/*.jar csci5308vm9@csci5308vm9.research.cs.dal.ca/home/csci5308vm9                            
    - sshpass -e ssh -tt -o StrictHostKeyChecking=no csci5308vm9@csci5308vm9.research.cs.dal.ca sudo mv /home/csci5308vm9/*.jar /opt/java/webapps     
    - sshpass -e ssh -tt -o StrictHostKeyChecking=no csci5308vm9@csci5308vm9.research.cs.dal.ca sudo systemctl restart gitlab-ci-demo.service                 
  artifacts:
    when: on_success
    paths:
      - $BACKEND_FOLDER_NAME/$TARGET_FOLDER_NAME/*.jar

frontend-deploy:
  stage: deploy
  script:
    - echo "Front-end Deployment started"
