variables:

  # Act as a varibale to be used further in YML file.
  TARGET_FOLDER_NAME: "target"

stages:
  # compiles this application.
  - compile

  # builds shipogle application.
  - build

  # tests shipogle application.
  - test

backend-compile:
  stage: compile
  tags:
    - ugrad
  image: maven:3.8.3-openjdk-17
  script:
    - echo "Cleaninig backend application."
    - cd backend
    - mvn clean compile
    - echo "Backend application cleaned successfully."
  rules:
    - changes:
        - backend/**/*

backend-build:
  stage: build
  tags:
    - ugrad
  image: maven:3.8.3-openjdk-17
  script:
    - echo "Started building backend application."
    - cd backend
    - mvn clean package
    - echo "Backend application has been built successfully."
  rules:
    - changes:
        - backend/**/*
  artifacts:
    when: on_success
    paths:
      - $TARGET_FOLDER_NAME/*.war

backend-test:
  stage: test
  tags:
    - ugrad
  image: maven:3.8.3-openjdk-17
  script:
    - echo "Backend application test started."
    - cd backend
    - mvn test
    - echo "Backend application Tested successfully."
  rules:
    - changes:
        - backend/**/*